"use client"

import { ReactNode } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Alert, AlertDescription } from "@/components/ui/alert"
import {
  FileText,
  Link,
  Lightbulb,
  Zap,
  BookOpen,
  List,
  Type,
  Globe
} from "lucide-react"

/* =======================
   Types
======================= */

interface GeneratedSection {
  heading: string
  summary: string
  content: string
  bullets?: string[]
  definition?: string
}

interface GeneratedWebpage {
  page_title?: string
  meta_description?: string
  executive_summary?: string
  sections?: GeneratedSection[]
  faq?: { question: string; answer: string }[]
  internal_linking_suggestions?: string[]
  schema_hints?: {
    article?: boolean
    faq?: boolean
  }
  raw_text?: string
}

interface GeoRecommendations {
  structured?: {
    missing_sections?: string[]
    content_formats?: string[]
    structural_improvements?: string[]
    final_summary?: string
  }
  raw_text?: string
}

interface GeoAgentResult {
  query: string
  ai_answer: string
  referenced_urls: string[]
  recommendations: GeoRecommendations | string
  generated_webpage: GeneratedWebpage
  timestamp?: string
}

interface GeoAgentPanelProps {
  result: GeoAgentResult
}

/* =======================
   Component
======================= */

export function GeoAgentPanel({ result }: GeoAgentPanelProps) {
  const structuredReco =
    typeof result.recommendations === "object"
      ? result.recommendations.structured
      : null

  const rawRecoText =
    typeof result.recommendations === "object"
      ? result.recommendations.raw_text
      : result.recommendations

  return (
    <div className="space-y-6">

      {/* ================= Query ================= */}
      <Card className="border-primary/20">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Zap className="h-5 w-5 text-primary" />
            Query Analysis
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-base font-medium">{result.query}</p>
        </CardContent>
      </Card>

      {/* ================= AI Answer ================= */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            AI-Generated Answer
          </CardTitle>
          <CardDescription>
            Complete response generated by the AI
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="h-[250px] overflow-y-auto rounded-md border p-4 bg-muted/30 whitespace-pre-wrap text-sm">
            {result.ai_answer || "No answer generated"}
          </div>
        </CardContent>
      </Card>

      {/* ================= URLs ================= */}
      {result.referenced_urls?.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Link className="h-5 w-5" />
              Referenced URLs
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-2">
            {result.referenced_urls.map((url, i) => (
              <a
                key={i}
                href={url}
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-2 text-sm text-primary hover:underline break-all"
              >
                <Globe className="h-4 w-4" />
                {url}
              </a>
            ))}
          </CardContent>
        </Card>
      )}

      {/* ================= RAW RECOMMENDATION OUTPUT ================= */}
      {rawRecoText && (
        <Card>
          <CardHeader>
            <CardTitle className="text-sm">
              GEO Analysis and recommendation.
            </CardTitle>
            <CardDescription>
              GEO agent recommendation.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <pre className="max-h-[300px] overflow-y-auto text-xs bg-muted/40 p-4 rounded whitespace-pre-wrap">
              {rawRecoText}
            </pre>
          </CardContent>
        </Card>
      )}

    </div>
  )
}
